version: '3.8'

services:
  database:
    container_name: mysql_db
    image: mysql/mysql-server:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: beespace
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: beespace01!
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일 위치
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test_network

  blue:
    image: ghtjd026/beespace:latest
    container_name: blue
    restart: on-failure
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - PROFILES=blue
      - ENV=blue
      - DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - DATASOURCE_URL=jdbc:mysql://mysql_db:3306/beespace
      - DATASOURCE_USERNAME=beespace
      - DATASOURCE_PASSWORD=beespace01!
      - GOOGLE_CLIENT_ID=18885979740-rli520t24fo8prcv0s3eet2ha1e64h2j.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - NAVER_CLIENT_ID=KsvXIMg4NMC9CRgZ2wvg
      - NAVER_CLIENT_SECRET=8dab6XYyIJ
      - KAKAO_CLIENT_ID=58a7abe7730157b4148ee0d1183c1624
      - KAKAO_CLIENT_SECRET=abtPdHmh8u3ZayR8ecP6aPmITvbsCvVi
      - GITHUB_CLIENT_ID=44e26d65e795c4a2283f
      - GITHUB_CLIENT_SECRET=3e34fb082712381ee928ad3b930e57756bbe1395
      - JWT_SECRET=dkanrjsk
      - AWS_ACCESS_KEY=AKIA6GBMHHNPU47GPNCI
      - AWS_SECRET_KEY=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
      - S3_BUCKET=creavi
    depends_on:
      - database
    networks:
      - test_network

networks:
  test_network: